namespace towers
{
    public enum TowerType
    {
        None,
        Stone,
        P,
        Q,
        D,
        G,
        E,
        R,
        B,
        Y,

        // Basic combinations
        Silver,
        Malachite,
        AsteriatedRuby,
        Jade,
        Quartz,

        // Intermediate combinations
        SilverKnight,
        PinkDiamond,
        VividMalachite,
        Uranium238,
        Volcano,
        Bloodstone,
        GreyJade,
        Gold,
        DarkEmerald,
        ParaibaTourmaline,
        DeepseaPearl,
        ChrysoBerylCatsEye,
        YellowSaphire,
        MonkeyKingJade,
        EgyptGold,
        LuckyChinese,
        CharmingLazurite,
        NorthernSabersEye,

        // Advanced combinations (3 combined towers)
        HugePinkDiamond,
        Uranium235,
        AntiqueBloodstone,
        EmeraldGolem,
        ElaboratelyCarvedTourmaline,
        RedCoral,
        DiamondCullinan,

        // Top
        KohINoorDiamond,
        DepletedKyparium,
        TheCrownPrince,
        GoldenJubilee,
        CarmenLucia,
        StarSapphire,
        SapphireStarOfAdam,

        // Secret
        Agate,
        Obsidian,
        FantasticMissShrimp,
    }
    // public enum TowerType
    // {
    //     None,
    //     Stone,
    //     P1,
    //     P2,
    //     P3,
    //     P4,
    //     P5,
    //     P6,
    //     Q1,
    //     Q2,
    //     Q3,
    //     Q4,
    //     Q5,
    //     Q6,
    //     D1,
    //     D2,
    //     D3,
    //     D4,
    //     D5,
    //     D6,
    //     G1,
    //     G2,
    //     G3,
    //     G4,
    //     G5,
    //     G6,
    //     E1,
    //     E2,
    //     E3,
    //     E4,
    //     E5,
    //     E6,
    //     R1,
    //     R2,
    //     R3,
    //     R4,
    //     R5,
    //     R6,
    //     B1,
    //     B2,
    //     B3,
    //     B4,
    //     B5,
    //     B6,
    //     Y1,
    //     Y2,
    //     Y3,
    //     Y4,
    //     Y5,
    //     Y6,
    // }
}